export const envButtons = document.querySelectorAll('.env-btn')
export const functionList = document.querySelector('.function-list')
export const resourceList = document.querySelector('.resource-list')
export const ratingStars = document.querySelectorAll('.rating-star')
export const saveButton = document.querySelector(".save-button")
export const loginButton = document.getElementById('loginButton')